### ISSUE TITLE
Docker based installation documentation missing

### ISSUE THREAD

**Issue by jayramr** [bpprc/database#1]
Hello, 

Do you have the docker based installation for this software? if yes kindly share the instructions

Thanks
Jay

**Comment by jayramr** [comment]
Hello,

Also please advise, what is the base python version does this installation support. I tried to build using conda, to create a different environemnt using python 3.9 , but i got an error with pandas version mismatch. Then I tried with pythin 2.7 , got error with Django version. Please advise 

Thanks

**Comment by jayramr** [comment]
With python3.9
```
  Running setup.py install for pandas ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pandas did not run successfully.
  │ exit code: 1
  ╰─> [957 lines of output]
```

**Comment by jayramr** [comment]
Hi, 
With python 3.6 , pip installation finished. Then i ran the migrate command, throwing error as "celery module" not found. I installed celery and run migrate command and got error as follows 

Btw I'm running this on a ubuntu server 20.04 . I ran below command with sudo access, still same error
```
 python manage.py migrate
Traceback (most recent call last):
  File "/opt/miniconda/envs/bpprc/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/miniconda/envs/bpprc/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/miniconda/envs/bpprc/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/miniconda/envs/bpprc/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
```

Please advise and let me know or if you have docker image for this pckage that would be awesome

**Comment by jayramr** [comment]
@Amrithasuresh 
Hi, 

Does the above error means, it is looking for an existing database up and running? because i wpuld need to run this on our HPC node or if it is on Docker image that would be great. 

Awaiting for your reply

Thanks
Jayaram

**Comment by Amrithasuresh** [comment]
Hi @jayramr, We don't have docker image for installation. I didn't update the repository for a long time. I moved to another institute and as of now I am busy. Please follow the installation instructions to use sqlite locally than postgres. Change the settings accordingly. Hope it helps.

**Comment by jayramr** [comment]
Thanks @Amrithasuresh  for the update.

I build the website to our onpremise setup with postgres and redis. Currently I'm facing only one issue with the reCaptcha for the domain verification when you "Submit the sequence for naming" tab. 

I'm still checking how to disable the reCaptcha field from Django. 

Thanks
Jay

**Comment by Amrithasuresh** [comment]
You can look into two place 1) The specific html page for "Submit the sequence.."  or 2) in the corresponding django forms page.

**Comment by jayramr** [comment]
Hi @Amrithasuresh i fixed the recaptcha by creating v2 and specified the keys which solves the problem. Now the site works good. Let me now explore how i can use this one. 

I'm closing this ticket for now. If i have any query with using this one, will open a new ticket
